### PR TITLE
feat: add eslint-plugin-vue-a11y for accessibility linting

### PR DESCRIPTION
**Pull request by gavmck**
# Description

Added the  [eslint Vue A11y plugin](https://www.npmjs.com/package/eslint-plugin-vue-a11y), which seems pretty much the same as the [JSX A11y plugin](https://www.npmjs.com/package/eslint-plugin-jsx-a11y) that I've had great success with so far.

This adds accessibility linting to eslint. I gave it a spin on patterns first and it found 17 errors, mostly keyboard events and one missing form label on a control, always good to catch!

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions
so we can reproduce.

- [x] Tried installing the plugin directly on patterns to see what it caught.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Designer has reviewed the change

### CODE REVIEW

**Review by shaunkrd — APPROVED** [review]
Fantastic 👍

**Review by alexrussell — APPROVED** [review]
Like it - approx how "angry" is it (in terms of the amount of errors versus warnings and sensible things in each category)?

**Review by denisgruba — APPROVED** [review]

**Comment by gavmck** [comment]
> Like it - approx how "angry" is it (in terms of the amount of errors versus warnings and sensible things in each category)?

@alexrussell I've installed the default recommended rules which are all errors, but looking at the rules they should probably be errors. Can't see anything I would disagree with off the top of my head.

**Comment by alexrussell** [comment]
> looking at the rules they should probably be errors

Totally get and agree in principle. Just worry about how much CI-blocking it might do to an existing codebase (I'm looking at PIO right now!) Obv we don't have to update in PIO, but yeah...

**Comment by gavmck** [comment]
> > looking at the rules they should probably be errors
> 
> Totally get and agree in principle. Just worry about how much CI-blocking it might do to an existing codebase (I'm looking at PIO right now!) Obv we don't have to update in PIO, but yeah...

@alexrussell Yeah I did wonder that! Maybe try a local install and see how bad it is? Once you get over the first install then it should be smooth sailing.

**Comment by andypattenden** [comment]
I know it's already approved and merged but just wanted to say this is a great addition👏

**Pull request merged**
