### PR TITLE
feat: change prettier to warn

### PR DESCRIPTION
**Pull request by spacecakes**
Changes Prettier rule from `error` to `warn`. 

Prettier can auto-fix these and I don't think it makes sense to have simple formatting deviations error out when we have more severe rules set to only warn. They usually aren't even errors, but rather only opinionated stylistic preferences.

### CODE REVIEW

**Comment by andypattenden** [comment]
Prettier isn't just auto-fixing the rules listed, they're overrides to the default prettier ruleset. There are other rules which are likely not auto-fixable so switching this to `warn` could create an inconsistent format in the code.

Prettier is meant to be opinionated to remove the discussion around stylistic preferences. Changing this to only warn would render prettier redundant and those discussions coming back which will slow development down.

**Comment by spacecakes** [comment]
> Prettier isn't just auto-fixing the rules listed, they're overrides to the default prettier ruleset. There are other rules which are likely not auto-fixable so switching this to `warn` could create an inconsistent format in the code.
> 
> Prettier is meant to be opinionated to remove the discussion around stylistic preferences. Changing this to only warn would render prettier redundant and those discussions coming back which will slow development down. They're considered errors as they break our code style rules.

They will still be auto-fixed though...?

**Comment by alexrussell** [comment]
In what way is errors on `""` over `''` impeding you? I don't get it. If you have autofixing on, as you should, it'll do its job.

I might be wrong, but I was under the impression that the autofixer only fixes errors and leaves warnings untouched (but emitting the warning, obviously). Your wording here suggests I'm wrong about this. If so then I don't mind _too much_ if it's an error or a warning as I rely on the autofixer.

That said, _if_ someone did a commit with something that went against the rules (i.e. would be autofixed, or should be an error that can't be autofixed) then it _should_ stop CI, etc., otherwise it'll never be addressed, so "error" does make sense to me.

So again, in what way is this impeding you?

**Comment by spacecakes** [comment]
> In what way is errors on `""` over `''` impeding you? I don't get it. If you have autofixing on, as you should, it'll do its job.
> 
> I might be wrong, but I was under the impression that the autofixer only fixes errors and leaves warnings untouched (but emitting the warning, obviously). Your wording here suggests I'm wrong about this. If so then I don't mind _too much_ if it's an error or a warning as I rely on the autofixer.
> 
> That said, _if_ someone did a commit with something that went against the rules (i.e. would be autofixed, or should be an error that can't be autofixed) then it _should_ stop CI, etc., otherwise it'll never be addressed, so "error" does make sense to me.
> 
> So again, in what way is this impeding you?

I'm not saying it's an impediment—I'm just saying I think it's silly to group auto-fixable cosmetic errors with ones that actually makes a difference to how the code runs. Prettier doesn't do this by default, but for some reason we have changed this.  I might be completely alone in thinking this, and might be completely wrong too. 

The reason I like the distinction between errors and warnings is that they pop up when typing and there are often several different stylistic errors at once until saving the file. By keeping Prettier yellow, I find it easier to focus on what actually needs fixing. This is usually how it works in other repos and it's just how I like to code. 

Vscode fixes the warnings without asking so yeah, that's why I don't see why it should be an error, but _I_ might be wrong here too in that the pipeline maybe won't auto-fix warning.

In any case, not that important to me. Just something I think would slightly improve the developer experience. I'll close the PR if my assumptions are incorrect and you all disagree with me. No biggie.

**Comment by alexrussell** [comment]
Innteresting. I can't say the "you have an issue here" DX has ever been a problem for me but fair enough if you inspect those enough to act on them immediately and it's frustrating that "real" problems are hidden behind "cosmetic" ones.

I think if the autofix will fix warnings without any special work _and_ we can ensure CI will "fail on warnings" (IIRC we can do this with something like `maxwarningns: 0`) then I'm happy enough.

I'm not sure you got me with my CI point above though. CI shouldn't be changing (fixing) the files - but it should be checking them and failing if they don't pass our checks. We definitely want the prettier rules to fail CI so that any issue that get through the editor save, precommit, etc. lint runs will not make it into main.

**Comment by spacecakes** [comment]
> I'm not sure you got me with my CI point above though. CI shouldn't be changing (fixing) the files - but it should be checking them and failing if they don't pass our checks. We definitely want the prettier rules to fail CI so that any issue that get through the editor save, precommit, etc. lint runs will not make it into main.

Sorry, I meant to say we should still be auto-fixing them _on commit_ so that they won't fail in the CI. If we can't do that for warnings then I understand why it's set up the way it is, but if we _can_ then I think my suggestion makes sense to separate cosmetic issues from the rest.

**Comment by spacecakes** [comment]
So here's an example: 

Screenshot_2021-11-09_at_08 44 01

Most of these errors are auto-fixable cosmetic ones (Stylelint is to blame here too) which tend to pop up whenever I work in a file since I don't care about whitespace, type of quotes or property sorting because I rely on formatters to auto-fix them for me. 

Some of these errors do require my attention though, and to make matters even inconsistent the `vue-attributes-order` rule is set to warn while still only dealing with cosmetic issues. 

When I save the file, most of the issues will go away leaving me with only what I have to act on myself: 
Screenshot 2021-11-09 at 08 48 49

So this is what I do. I just wish I didn't need to and could separate the issues from the noise more easily before saving. Again not a big issue (and not a big fix either 👆), but something that have been bugging me a little.

**Comment by alexrussell** [comment]
Cool, then yeah what I said is how I feel about this:

> I think if the autofix will fix warnings without any special work and we can ensure CI will "fail on warnings" (IIRC we can do this with something like `maxwarningns: 0`) then I'm happy enough.

**Comment by andypattenden** [comment]
So I think something we might want to think about here is what we consider an error. IMO an error should be thrown when the code breaks the linting rules, whether that be stylistic or otherwise.

I can see why there is confusion here though due to how the Vue config which we extend considers errors vs warnings. Anything in the [essential ruleset](https://github.com/vuejs/eslint-plugin-vue/blob/master/lib/configs/essential.js) is classed as an error and anything else in their recommended rulesets ([recommended](https://github.com/vuejs/eslint-plugin-vue/blob/master/lib/configs/recommended.js), [strongly-recommended](https://github.com/vuejs/eslint-plugin-vue/blob/master/lib/configs/strongly-recommended.js)) is a warning. Depending on what we consider an error, we _could_ switch all the Vue rules to error level.

> Prettier doesn't do this by default, but for some reason we have changed this

The prettier plugin has actually been configured exactly how they recommend [here](https://github.com/prettier/eslint-plugin-prettier#recommended-configuration) (bar some overrides to suit our codestyle).

My worry with switching everything to warnings is that it then relies on all consumers setting up their lint scripts to add the CLI option. We also have a lot of outstanding warnings (JSdocs) which would suddenly all need addressing.

**Comment by spacecakes** [comment]
Reviving this conversation as I still think this is necessary and we never came to a conclusion last time. Granted, it's not a huge deal but it _is_ something that has annoyed me for two years. 

This log from CodeBuild is what prompted me to revive this discussion today:
Screenshot 2022-10-25 at 15 55 15

Because Prettier is set to `error` rather than `warn`, the build failed because of an additional blank line and a missing comma. But it was perfectly okay with having a bunch of unused variables, missing documentation, forbidden null assertions and 200 more warnings.

This does not make sense to me. As mentioned before, Prettier issues are also auto-fixable so they will go away when linted or saved. That too makes them less of an error and more of a warning IMO.

What do you think, a year later? 😁

**Comment by spacecakes** [comment]
Closing this as it should probably be an issue, but still interested in hearing your thoughts

**Pull request closed without merging**
