### PR TITLE
Moving to Github NPM registry

### PR DESCRIPTION
**Pull request by strottos**
- Moving from NPM registry to Github NPM registry
- Fixed audit problems

### CODE REVIEW

**Comment by strottos** [comment]
Any objections to this one chaps. The 4.0.0 version should still work out of NPM registry but I understand we're moving to Github NPM registry now from Nick. Maybe I should bump to 5.0.0 for example?

**Comment by andypattenden** [comment]
If we move this we'll no longer be able to get later versions from all our other repositories.

**Comment by strottos** [comment]
Unless we move those other repositories (which I thought was the plan but maybe not)...

**Comment by andypattenden** [comment]
It is but needs to be a coordinated effort, we have to move all packages in the org over in one go.

**Comment by alexrussell** [comment]
Yeah we have to ensure that all packages are available in GH reg because as soon as we say "`@boughtbymany` is now in GH" it'll be looking there for _all_ `@boughtbymany` packages, right?

**Comment by alexrussell** [comment]
Also this is a public package so we need to be careful about how we want to handle these. Do we want to make it private and move to GH or not? If we leave it on npm and public, we may need a different scope or no scope.

Also see https://paper.dropbox.com/doc/Migration-to-GitHubs-JS-package-registry-C5D9mgVH0wzYyMYIpR3qo @strottos

**Comment by strottos** [comment]
Yeah OK, point taken, maybe this PR can be closed until such a time then (or delete the branch, not like it's hard to redo). We'll work around this in another way in the meantime. Thanks anyway 👍

**Comment by strottos** [comment]
> Also this is a public package so we need to be careful about how we want to handle these. Do we want to make it private and move to GH or not? If we leave it on npm and public, we may need a different scope or no scope.
> 
> Also see https://paper.dropbox.com/doc/Migration-to-GitHubs-JS-package-registry-C5D9mgVH0wzYyMYIpR3qo @strottos

On this point (which I hadn't realised was an issue, I assumed they were all private, though no reason they would be). That may mean we need a different scope as you say and these probably should also be changed to `@manypets` at some point. Maybe `@manypetspvt` and `@manypets` or something like that. I'll close this off for now anyway.

**Comment by andypattenden** [comment]
Moving packages to a new org might be a way we could do a gradual migration

**Pull request closed without merging**
