### PR TITLE
feat: update eslint vue a11y plugin

### LINKED ISSUE #27: Change the eslint-plugin-vue-a11y peer dependency
[eslint-plugin-vue-a11y](https://github.com/maranran/eslint-plugin-vue-a11y) appears to be no longer maintained and is causing peer-dependency installation issues on npm v7+.

Could we fix this by using the more up to date [eslint-plugin-vuejs-accessibility](https://github.com/vue-a11y/eslint-plugin-vuejs-accessibility) instead?

CC: @gavmck a while back now, I remember you suggested there was an issue with using eslint-plugin-vuejs-accessibility, can you remember what the issue was? If not, I'll run some tests with and create a PR for this when I get a mo.

### PR DESCRIPTION
**Pull request by DanWebb**
**Description**

- Upgrades `eslint-plugin-vue-a11y` to the newer `eslint-plugin-vuejs-accessibility`
- Changes existing a11y rules within vue.js to map to the same rules provided by `eslint-plugin-vuejs-accessibility`
- Fixes #27

**Testing**

- Installed the new version on https://github.com/boughtbymany/careers
- Updated the eslint vue-a11y plugin on the repo
- `npm run lint`
- Some new a11y warnings were thrown for anchor content, due to slightly different implementation of the rules between the packages

**Upgrading**

- Projects using less than NPM v7 will need to change their `eslint-plugin-vue-a11y` dependency to `eslint-plugin-vuejs-accessibility` to prevent an error being thrown due to the missing peer dependency

### CODE REVIEW

**Review by alexrussell — COMMENTED** [review]
So this looks like a straight replacement, which is nice. ~Were there any changes when you tested this (i.e. stuf picked up or needing a small change?) or is it a drop-in and no changes?~ Edit: just seen that you mention this in the PR desc!

I think because of the peer dep change (and people on npm <7) we should _probably_ call this major, even if the intention of the package is a drop-in replacement

**Comment by DanWebb** [comment]
Thanks for the review @alexrussell!

**New warnings**
The differences will be subtle, in the case I mention the rule that got flagged was `anchor-has-content`, here's the docs for that:

- [eslint-plugin-vue-a11y docs](https://github.com/maranran/eslint-plugin-vue-a11y/blob/master/docs/rules/anchor-has-content.md)
- [eslint-plugin-vuejs-accessibility docs](https://github.com/vue-a11y/eslint-plugin-vuejs-accessibility/blob/main/docs/anchor-has-content.md)

eslint-plugin-vue-a11y ran [this file (generated by nuxt init)](https://github.com/boughtbymany/careers/blob/main/components/Tutorial/Tutorial.vue) without warnings. The new eslint-plugin-vuejs-accessibility flagged that in  the content of the `<a>` doesn't count as "accessible content", I'd say it's correct to flag this as all it contains is an SVG with no aria or title attributes.

**Version change**
I was torn between this, but I think you're right, people on NPM < 7 should expect to fix some things meaning this is a breaking (major). I'll update the version number 👍

**Comment by alexrussell** [comment]
Thanks for the detail. I don't have access to that repo but fair enough - this looks like it'd likely be a "patch" fixup to the accessibility plugin if it were the same one, so not a massive deal to call out (though it _may_ break pipelines with no changes other than this dep update). The change to a major will help communicate this anyway.

Not sure if v2 `package-lock.json`s still contain the `package.json` verison number (and it's a lot to ask GitHub to unfurl that change!) so if it does can you update that too (`npm i` should do it)?

**Comment by DanWebb** [comment]
✅ Done

**Review by alexrussell — APPROVED** [review]

**Pull request merged**
